runtime: python39  # Set the Python version to 3.9 (you can adjust based on your version)

entrypoint: gunicorn -b :$PORT api.wsgi:app --timeout 120 --workers 3


env_variables:
  DJANGO_SETTINGS_MODULE: "api.settings"  # Replace 'api' with the name of your settings module
  SECRET_KEY: "django-insecure-=cldztbc4jg&xl0!x673!*v2_=p$$eu)=7*f#d0#zs$44xx-h^"  # Set a secure value for production
  DEBUG: "True"

handlers:
- url: /static
  static_dir: static/

automatic_scaling:
  target_cpu_utilization: 0.6
  min_instances: 1
  max_instances: 2
